name: fly_to_target
description: "A Flutter package for animating multiple widgets flying to target positions simultaneously with customizable paths and effects."
version: 1.5.0
homepage: https://github.com/anies1212/fly_to_target
repository: https://github.com/anies1212/fly_to_target
issue_tracker: https://github.com/anies1212/fly_to_target/issues

topics:
  - animation
  - ui
  - widget
  - flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
